resources:
  - name: kernelci-core
    type: git
    source:
      uri: ((kci-core-url))
      branch: ((kci-core-branch))

  - name: kernelci-concourse
    type: git
    source:
      uri: ((kci-concourse-url))
      branch: ((kci-concourse-branch))

  - name: kernel-repo
    type: git
    source:
      uri: ((kernel-repo-url))
      branch: ((kernel-repo-branch))

jobs:
  - name: trigger
    public: true
    plan:
      - get: kernelci-core
      - get: kernelci-concourse  

      # - task: check-configs
      #   file: kernelci-concourse/tasks/build-trigger.yaml
      #   params:
      #     CONFIG_LIST: ((config-list))
      #     KCI_STORAGE_URL: ((kci-storage-url))

      - get: kernel-repo
        trigger: true
        # params: {depth: 1}
        # params: {repository: some-other-repo}
        # kernel-git-url: https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux.git
        # kernel-git-branch: to-build
          
      - task: check-new-commit
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: kernelci/build-base}

          inputs:
            - name: kernelci-core

          outputs:
            - name: outputs
              
          params:
            BUILD_CONFIG: ((build-config))
            KCI_STORAGE_URL: ((kci-storage-url))
          run:
            dir: kernelci-core
            path: bash
            args:
              - -xc
              - |
                env
                pwd
                COMMIT=$(./kci_build check_new_commit --build-config $BUILD_CONFIG --storage $KCI_STORAGE_URL)

      - task: update-commit
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: kernelci/build-base}

          inputs:
            - name: kernelci-core
            - name: kernel-repo
              
          outputs:
            - name: trigger-outputs
              
          params:
            BUILD_CONFIG: ((build-config))
            KCI_API_URL: ((kci-api-url))
            KCI_API_TOKEN: ((kci-api-token))
            
          run:
            dir: kernelci-core
            path: bash
            args:
              - -xc
              - |
                env
                KDIR=../kernel-repo
                OUTPUT=../trigger-outputs
                COMMIT=$(./kci_build describe --build-config $BUILD_CONFIG --kdir $KDIR | head -1)

                if [[ ! -z $COMMIT ]]; then
                  ./kci_build update_last_commit --build-config $BUILD_CONFIG --commit $COMMIT --api $KCI_API_URL --db-token $KCI_API_TOKEN
                fi

                ./kci_build generate_fragments --build-config $BUILD_CONFIG --kdir $KDIR
                ./kci_build list_kernel_configs --build-config $BUILD_CONFIG --kdir $KDIR | tee $OUTPUT/list_kernel_configs.txt

      - load_var: kernel-configs
        file: trigger-outputs/list_kernel_configs.txt
        
      - task: create-builds
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: concourse/concourse}

          inputs:
            - name: kernelci-concourse
            - name: trigger-outputs  

          params:
            KERNEL_CONFIGS: ((.:kernel-configs))

          run:
            path: bash
            args:
              - -xc
              - |
                env
                ls -l

                
  - name: build
    public: true
    plan:
      - get: kernelci-core
      - get: kernel-repo
        passed: [trigger]
        
      - task: build
        config:
          platform: linux

          params:
            BUILD_ENV: ((build-env))
            ARCH: ((arch))
            DEFCONFIG: defconfig
            
          image_resource:
            type: docker-image
            source: {repository: kernelci/build-((build-env))_((arch))}

          inputs:
            - name: kernelci-core
            - name: kernel-repo
              
          run:
            dir: kernelci-core
            path: bash
            args:
              - -xc
              - |
                KDIR=../kernel-repo
                CCACHE_DISABLE=true
                env
                ./kci_build build_kernel --arch $ARCH --build-env $BUILD_ENV --defconfig $DEFCONFIG --kdir $KDIR

