---
platform: linux

image_resource:
  type: docker-image
  source: {repository: kernelci/build-base}

inputs:
  - name: monitor-out
    
run:
  path: ls
  args: [-alR]
  #path: ./kernelci-concourse/tasks/test.py
  #path: ./kernelci-concourse/tasks/monitor.sh
