---
platform: linux

image_resource:
  type: docker-image
  source: {repository: kernelci/build-base}

inputs:
  - name: kernelci-core
  - name: kernelci-concourse
  - name: kernel-repo
    
params:
  BUILD_CONFIG: khilman
  KCI_STORAGE_URL: https://storage.staging.kernelci.org

run:
   path: ./kernelci-concourse/tasks/build-trigger.sh
