---
platform: linux

image_resource:
  type: docker-image
  source: {repository: kernelci/build-base}

inputs:
  - name: kernelci-core
  - name: kernelci-concourse
  - name: monitor-out
    
run:
   path: ./kernelci-concourse/tasks/build-trigger.sh
