---
platform: linux

image_resource:
  type: docker-image
  source: {repository: kernelci/build-base}

inputs:
  - name: kernelci-core
  - name: kernelci-concourse

params:
  CONFIG_LIST: "mainline"
  KCI_STORAGE_URL: https://storage.staging.kernelci.org
  
outputs:
  - name: monitor-out
    
run:
  path: ./kernelci-concourse/tasks/monitor.sh
