---
platform: linux

image_resource:
  type: docker-image
  source: {repository: kernelci/build-base}

inputs:
  - name: kernelci-core
  - name: kernelci-concourse

params:
  CONFIG_LIST: "next"
  KCI_STORAGE_URL: https://storage.staging.kernelci.org
  
run:
  # path: ls
  # args: [-alR]
  path: ./kernelci-concourse/tasks/test.py
