---
platform: linux

image_resource:
  type: docker-image
  source: {repository: kernelci/build-base}

inputs:
  - name: kernelci-core
  - name: kernelci-concourse

run:
  # path: ls
  # args: [-alR]
  path: ./kernelci-concourse/tasks/test.py
